# Generated by Django 3.2.2 on 2021-05-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_group_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='context',
            field=models.CharField(blank=True, choices=[('DEPARTMENT', 'Department'), ('FACULTY', 'Faculty'), ('LEVEL', 'Level')], max_length=20),
        ),
    ]
