# Generated by Django 3.2.2 on 2021-05-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210514_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='dashboard.Attachment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='threads',
            field=models.ManyToManyField(blank=True, to='dashboard.MessageThread'),
        ),
    ]
