# Generated by Django 3.2.2 on 2021-05-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_message_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagethread',
            name='subject',
        ),
    ]
