# Generated by Django 3.2.2 on 2021-05-17 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_remove_messagethread_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receivers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
