# Generated by Django 3.2.2 on 2021-05-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_message_receivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
