# Generated by Django 3.2.2 on 2021-05-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_staffprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
