# Generated by Django 3.2.2 on 2021-05-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('DEFAULT', 'Default')], max_length=100),
        ),
    ]
