# Generated by Django 3.2.2 on 2021-05-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(max_length=20, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.CharField(max_length=20, verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
    ]
